inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    # uncomment if use rails cops
    - "config/rails.yml"
    # uncomment if use rspec cops
    - "config/rspec.yml"

Rails/SaveBang:
  Enabled: false

Style/SymbolProc:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.5
  # uncomment if use rails cops
  TargetRailsVersion: 5.1
  Exclude:
    - "vendor/**/*"
    - "db/schema.rb"
    - "bin/*"
    - "Guardfile"
    - "db/migrate/**/*"
    - 'frontend/**/*'

Security/Open:
  Exclude:
    - "app/models/scraping/disney_land.rb"
    - "app/models/scraping/disney_sea.rb"
Metrics/MethodLength:
  Exclude:
    - "app/models/scraping/disney_land.rb"
    - "app/models/scraping/disney_sea.rb"
Metrics/AbcSize:
  Exclude:
    - "app/models/scraping/disney_land.rb"
    - "app/models/scraping/disney_sea.rb"
